version: '3.9'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mayorista_db_container-1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "0000"
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - corocora-network

  factura-generator:
    build:
      context: ./facturaGenerator
      dockerfile: Dockerfile
    container_name: factura-generator-1
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - corocora-network
    environment:
      - R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
      - R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
      - R2_ENDPOINT_URL=${R2_ENDPOINT_URL}
      - R2_BUCKET_NAME=${R2_BUCKET_NAME}
      - R2_PUBLIC_URL=${R2_PUBLIC_URL}


networks:
  corocora-network:
    driver: bridge